units:
  - path: /autoware/localization
    type: and
    list:
      - { type: link, link: /autoware/localization/topic_rate_check/transform }
      - { type: link, link: /autoware/localization/topic_rate_check/pose_twist_fusion }

  - path: /autoware/localization/topic_rate_check/transform
    type: diag
    node: topic_state_monitor_transform_map_to_base_link
    name: localization_topic_status

  - path: /autoware/localization/topic_rate_check/pose_twist_fusion
    type: diag
    node: topic_state_monitor_pose_twist_fusion_filter_pose
    name: localization_topic_status
